id: P001652
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC354
  title: དཔྱད་རྩོམ།
  author: ''
  volumes:
    44ef6eeb7b0745f5ab8d631af23e0632:
      image_group_id: I2PD18509
      title: ''
      volume_number: 1
      total_pages: 491
      base_file: v001.txt
